In [1]:
import warnings
warnings.filterwarnings("ignore")

import tensorflow as tf

### reduce_mean

In [2]:
v = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
sess = tf.InteractiveSession()
tf.reduce_mean(v).eval()  #对所有元素求平均值

3.5

In [3]:
tf.reduce_mean(v,0).eval()  #对0轴,即对所有列求平均值

array([2.5, 3.5, 4.5], dtype=float32)

In [4]:
tf.reduce_mean(v,1).eval()  #对所有1轴,即对所有行求平均值

array([2., 5.], dtype=float32)

In [5]:
sess.close()

### clip_by_value

In [6]:
v = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
sess = tf.InteractiveSession()

In [7]:
tf.clip_by_value(v,2.5,4.5).eval()   #小于2.5的值都设置为2.5,大于4.5的值都设置为4.5

array([[2.5, 2.5, 3. ],
       [4. , 4.5, 4.5]], dtype=float32)

In [8]:
sess.close()

### where

In [9]:
v1 = tf.constant([1.0,2.0,3.0,4.0])
v2 = tf.constant([4.0,3.0,2.0,1.0])
sess = tf.InteractiveSession()

In [10]:
tf.greater(v1,v2).eval()

array([False, False,  True,  True])

In [11]:
tf.where(tf.greater(v1,v2),v1,v2).eval()

array([4., 3., 3., 4.], dtype=float32)

In [12]:
sess.close()